server:
  port: 8080

spring:
  profiles:
    include: env
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    # jpa setting
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        show_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
        # reserved words error config (add backticks)
        auto_quote_keyword: false
        globally_quoted_identifiers: false
    open-in-view: true
    defer-datasource-initialization: false

springdoc:
  version: '@project.version@'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none
  paths-to-match:
    - /**
#    - /api/**


logging:
  level:
    com:
      donghyun:
        EGG: debug
